spring:
  config:
    activate:
      on-profile: local

  cloud:
    aws:
      endpoint: http://192.168.50.2:4566
      region:
        static: ap-northeast-2
      credentials:
        profile: localstack
      s3:
        endpoint: http://192.168.50.2:4566
        path-style-access-enabled: true

  data:
    redis:
      host: 192.168.50.2
      port: 6379
      password: ${valkey_password}