server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import:
      - "optional:classpath:/application-common-${spring.profiles.active}.yml"
      - "optional:aws-secretsmanager:user-svc/secure-config"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service
        format_sql: true
    show-sql: true
    open-in-view: false

jwt:
  secret: ${jwt_secret}
  access-token-expiry: 3600000  # 1 hour in milliseconds
  refresh-token-expiry: 604800000  # 7 days in milliseconds

internal:
  api:
    key: ${internal_api_key}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ticketqueue.user: DEBUG
    org.hibernate.SQL: DEBUG

recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify
  secret: ${recaptcha_secret:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
