spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://192.168.50.2:5432/ticket_queue?currentSchema=user_service,common
    username: user_svc_user
    password: ${db_password}
    driver-class-name: org.postgresql.Driver