server:
  port: 8083

spring:
  application:
    name: queue-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

  data:
    redis:
      host: 192.168.50.2
      port: 6379

queue:
  batch:
    size: 10  # Approve 10 users per second
    interval: 1000  # 1 second in milliseconds
  token:
    ttl: 600  # 10 minutes in seconds
  max-capacity: 50000  # Maximum users per schedule queue
  active-user:
    ttl: 600  # 10 minutes - prevent duplicate queue entry

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ticketqueue.queue: DEBUG
